tasks:
  - key: domain-events
    typeKey: ERROR_DOMAIN_EVENTS
    stateKey:
    name: "Process error's in domain events table"
    scheduleType: "CRON"
    channelType: "QUEUE"
    endDate:
    startDate:
    delay:
    cronExpression: "0 0 12 * * ?" # every day at 11:00 AM
    data: |
    targetMs: entity
