---
topics:
  - key: DOMAIN.EVENT.HANDLER
    groupId: main-processor
    typeKey: domain_event_handler
    topicName: event.xm.db
    retriesCount: 1
    backOffPeriod: 10000
    deadLetterQueue: xm_common_errors
    logBody: false
